# You can either specify your configurations variables here or pass them as build arguments

# Serial number, if undefined, it is generated from the current date and time
#SERIAL=''

# Time To Live in seconds
#TTL='3600'

# Refresh time in seconds
#REFRESH='3600'

# Retry time in seconds
#RETRY='1800'

# Expiration time in seconds
#EXPIRE='604800'

# Negative cache Time To Live in seconds
#NEGATIVE_CACHE_TTL='1800'

# If defined, allows transfer to that address (master to secondary)
#TRANSFER=''

# If defined, resolves foreign names for the clients named here ('any' makes an
# open resolver); unset the server answers for its own zones only
#RECURSION=''

# If defined, the number of identical answers one client prefix gets per second
#RATE_LIMIT=''

# Mail server for the MX record of every domain, default '@' means the domain itself
#MAILSERVER=''

# Logging severity
#SEVERITY='warning'

# Subdomains that are generated by default
#DEFAULT_SUBDOMAINS='www'

# IP that is used by default
#DEFAULT_IP='12.34.56.78'

# default domains are configured to go to the DEFAULT_IP and to contain the DEFAULT_SUBDOMAINS
#DEFAULT_DOMAINS=''

# Handle special cases
# Format:
#  - Lines
#  - starting with with domain name separated by =
#  - then separated by ; the fields: IP, space separated subdomains, any number of additional lines added to domain
# if IP field is empty, DEFAULT_IP is used
# if subdomains is empty, DEFAULT_SUBDOMAINS is used
#DOMAINS=''
