# You can either specify your configurations variables here or pass them as build arguments

# Serial number, if undefined, it is generated from the current date and time
#SERIAL=''

# Time To Live in seconds
#TTL='3600'

# Refresh time in seconds
#REFRESH='3600'

# Retry time in seconds
#RETRY='1800'

# Expiration time in seconds
#EXPIRE='604800'

# Negative cache Time To Live in seconds
#NEGATIVE_CACHE_TTL='1800'

# If defined, allows transfer
#TRANSFER=''

# Logging severity
#SEVERITY='warning'

# Subdomains that are generated by default
#DEFAULT_SUBDOMAINS='www'

# IP that is used by default
#DEFAULT_IP='212.51.159.193'

# default domains are configured to go to the DEFAULT_IP and to contain the DEFAULT_SUBDOMAINS
#DEFAULT_DOMAINS=''

# Handle special cases
# Format:
#  - Lines
#  - starting with with domain name separated by =
#  - then separated by ; the fields: IP, space separated subdomains, any number of additional lines added to domain
# if IP field is empty, DEFAULT_IP is used
# if subdomains is empty, DEFAULT_SUBDOMAINS is used
#DOMAINS=''
